[build]
  base    = "music-player/frontend"   # <─ Netlify cd’s here, runs npm install
  command = "npm run build"           # uses the frontend package.json
  publish = "dist"                    # uploads dist/
