[build]
  base    = "music-player/frontend"
  command = "npm run build"
  publish = "dist"              # ←  this line

[build.environment]
  VITE_API_URL = "https://kpop-player-production.up.railway.app"
